server:
  port: 8082
spring:
  application:
    name: order-server
grpc:
  server:
    port: 8072
# 定义调用商品服务的GRPC
product.server.address: localhost:8073
# 定义调用优惠券服务的GRPC
coupon.server.address: localhost:8071